### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by alsotang**

### CODE REVIEW

**Comment by andrezsanchez** [comment]
What is this trying to fix? `err.name = name` was written so that certain browsers return the stack trace correctly, as the preceding comment suggests (though perhaps a bit too vaguely). I suppose I should get around to adding browser tests so that this is obvious.

**Comment by alsotang** [comment]
oh.. because I find `err` var not used any more after the assign.
maybe it's a trick here. I should close this pr...sorry

**Comment by andrezsanchez** [comment]
It's fine, yes it is a bit odd. That line affects the value of `err.stack`, so it does in fact have an effect.

**Comment by alsotang** [comment]
alright, this line is somehow tricky. thx for explaintion

2015-11-16 19:31 GMT+08:00 Andre Z Sanchez <notifications@github.com>:

**Pull request closed without merging**
